site_name: Recetas de Mamá
theme:
  name: material 
  font:
    text: Inconsolata
  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: white
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search
  - literate-nav:
      nav_file: navigation.md
